### ISSUE TITLE
Run read-only tests on each PR

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-react-e2e-tests#23]
We'd like to run a very basic smoke test on each PR.

W/o making any transactions or changes.

Post the result as a comment in the target PR.

**Comment by francovenica** [comment]
We should create a safe exclusively for this, with an specific amount of ERC20/721 tokens, Tx in the Queue tab and History tab and a fixes list of owners. This would make for a safe that is predictable and should always respond to the same test.

Test would be:
Does it has  the A,B,C ERC20 tokens available? 
Does it has the A,B,C ERC721 tokens available? 
Does it has the Tx nonce "x" in the Queue tab, can I open its details?
Does it has the Tx nonce "x-1", "x-2", "x-3",  in the History tab, can I open their details? These should be different types of tx since we had issues in the past were opening tx details would cause the app to crash
Does the list of owners is showing and they are all there?
Does it shows "x out of y" policies, making sure y is not 0?
Did the safe and owners loaded with their names?
Did the address book stored the names of the safe and owners after loading?
Does the apps are loading? we can check for tx builder and WC since they are the most popular ones
